[package]
name = "cluu-kernel-rust"
version = "0.0.1"
authors = ["Balazs Valkony"]
edition = "2024"

[profile.dev]
panic = "abort" # disable stack unwinding on panic

[dependencies]
rlibc = "1.0.0"
spin = "0.10.0"
x86 = "0.52.0"
x86_64 = "0.15.4"
bitflags = "2.10.0"
log = "0.4.29"

